/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5-dev at Wed Jan 27 11:02:47 2016. */

#include "SmartStore.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SSMsg_fields[18] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SSMsg, msgtype, msgtype, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, result, msgtype, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, SSMsg, devinfo, result, &DevInfo_fields),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, name, devinfo, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, status, name, 0),
    PB_FIELD(  6, MESSAGE , REPEATED, CALLBACK, OTHER, SSMsg, devlist, status, &Dev_fields),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, nwk_addr, devlist, 0),
    PB_FIELD(  8, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, ep, nwk_addr, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, on_off, ep, 0),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, SSMsg, dev, on_off, &Dev_fields),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, date_time, dev, 0),
    PB_FIELD( 12, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, ep_name, date_time, 0),
    PB_FIELD( 13, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, arm, ep_name, 0),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, SSMsg, w_mode, arm, 0),
    PB_FIELD( 15, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, ieee, w_mode, 0),
    PB_FIELD( 16, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, device_id, ieee, 0),
    PB_FIELD( 17, STRING  , OPTIONAL, STATIC  , OTHER, SSMsg, zone_type, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t Dev_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, Dev, ieee, ieee, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, Dev, nwk_addr, ieee, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, Dev, node_name, nwk_addr, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, Dev, online, node_name, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, Dev, node_status, online, 0),
    PB_FIELD(  6, MESSAGE , REPEATED, CALLBACK, OTHER, Dev, eps, node_status, &EPS_fields),
    PB_LAST_FIELD
};

const pb_field_t DevInfo_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, DevInfo, manufacture, manufacture, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, DevInfo, model, manufacture, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DevInfo, sn, model, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, DevInfo, mac, sn, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, DevInfo, sw_ver, mac, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, DevInfo, hw_ver, sw_ver, 0),
    PB_LAST_FIELD
};

const pb_field_t EPS_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, EPS, profile_id, profile_id, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, EPS, device_id, profile_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, EPS, zone_type, device_id, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, EPS, ep, zone_type, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, EPS, ep_name, ep, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, EPS, rid, ep_name, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, EPS, arm, rid, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SSMsg, devinfo) < 65536 && pb_membersize(SSMsg, devlist) < 65536 && pb_membersize(SSMsg, dev) < 65536 && pb_membersize(Dev, eps) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SSMsg_Dev_DevInfo_EPS)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SSMsg, devinfo) < 256 && pb_membersize(SSMsg, devlist) < 256 && pb_membersize(SSMsg, dev) < 256 && pb_membersize(Dev, eps) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SSMsg_Dev_DevInfo_EPS)
#endif


